### ISSUE TITLE
电脑小白借地问一下，似乎是被几个网站屏蔽了，该怎么办？

### ISSUE THREAD

**Issue by rock-1995** [Deadfxck/TCPioneerConfigUpdate#1]
我之前通过添加 域名=IP 的方式，能够很顺畅的打开nyaa.si，不太稳定地可以用civitai.com。但前几天这两个我都打不开了。浏览器反馈回来的如下：
civitai.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

但其他一些网站，比如pixiv，就没问题

**Comment by Deadfxck** [comment]
试一试？我也不是太懂
https://blog.csdn.net/qq_39939541/article/details/131621139

**Comment by Deadfxck** [comment]
或者添加几个method,原项目里面有配置方法
